version: '3'

dotenv: [".env"]

tasks:

    ###################################################
    # Postgres
    ###################################################
    runpostgres:
        desc: Start a Postgres instance in Docker
        cmds:
        - docker rm -f pg-local || true # Delete container if exists
        -  docker run --name pg-local -e POSTGRES_USER=testuser -e POSTGRES_DB=companies -e POSTGRES_PASSWORD=password -p 5432:5432 --detach ankane/pgvector
    pgcli:
        desc: Enter postgres CLI inside container
        cmds:
        -  docker exec -it pg-local psql -U testuser -d companies
    newmigration:
        desc: Create a new migration file. Example - task newmigration -- add_new_cols
        cmds:
        - goose -dir ./migrations create {{.CLI_ARGS}} sql
    migrate:
        desc: Run all migrations/seeds
        cmds:
        - goose -dir ./migrations -table _migrations postgres "postgresql://testuser:password@localhost:5432/companies" up
