-- +goose Up
-- +goose StatementBegin

INSERT INTO company (name, description) VALUES ('TechVantage Solutions', 'Welcome to TechVantage Solutions, a cutting-edge technology firm driving innovation across industries. Our team of experts specializes in delivering bespoke software solutions, leveraging AI, IoT, and blockchain technologies. With a focus on customer-centricity, we empower businesses to thrive in the digital era. Whether you need scalable enterprise applications or advanced data analytics, TechVantage Solutions has you covered. Join us on the journey to transform your business and stay ahead in the rapidly evolving technological landscape.');
INSERT INTO company (name, description) VALUES ('Nature''s Haven Retreats', 'At Nature''s Haven Retreats, we craft unforgettable experiences that rejuvenate your mind, body, and soul. Nestled amidst breathtaking landscapes, our wellness retreats offer holistic healing, yoga, meditation, and adventure activities to help you reconnect with nature. Our passionate team of wellness experts and eco-adventurers are committed to creating transformative journeys, promoting well-being and sustainable living. Discover harmony and inner peace as you immerse yourself in the embrace of pristine natural surroundings at Nature''s Haven Retreats.');
INSERT INTO company (name, description) VALUES ('GourmetXpress', 'Indulge your taste buds with GourmetXpress, your ultimate culinary partner. We curate a world of flavors, bringing exquisite gourmet ingredients to your doorstep. From rare spices to premium meats and artisanal delicacies, our products are sourced from the finest producers worldwide. Whether you''re a home chef or a Michelin-starred restaurant, GourmetXpress caters to your culinary aspirations. Elevate your gastronomic experiences with our handpicked selection, delivered with care and precision.');
INSERT INTO company (name, description) VALUES ('PlayWave Studios', 'Enter the realm of imagination with PlayWave Studios, where creativity knows no bounds. As a leading game development company, we breathe life into captivating virtual worlds. Our team of visionaries, designers, and programmers collaborates to produce immersive gaming experiences for players of all ages. From action-packed adventures to educational simulations, each game we create is a masterpiece of storytelling and interactivity. Embark on thrilling quests and discover new dimensions of entertainment with PlayWave Studios.');
INSERT INTO company (name, description) VALUES ('SustainaTech Innovations', 'At SustainaTech Innovations, we''re committed to a greener and cleaner future. As pioneers in eco-friendly technology, we design and manufacture sustainable solutions to tackle pressing environmental challenges. From solar-powered devices to energy-efficient appliances, our products are designed to reduce carbon footprints and promote responsible consumption. Join us in the movement towards a more sustainable world, where technology and environmental stewardship go hand in hand. Together, let''s shape a brighter tomorrow with SustainaTech Innovations.');
INSERT INTO company (name, description) VALUES ('NovaTech Robotics', 'Welcome to NovaTech Robotics, where innovation meets automation. As pioneers in robotics technology, we engineer state-of-the-art robotic solutions for industrial and domestic applications. From smart manufacturing systems to intelligent home assistants, our cutting-edge robots are designed to enhance productivity and simplify daily life. Join us in shaping the future of automation, where precision and efficiency converge, with NovaTech Robotics.');
INSERT INTO company (name, description) VALUES ('Wanderlust Adventures', 'Embark on unforgettable journeys with Wanderlust Adventures, your travel companion. We curate extraordinary travel experiences that take you off the beaten path to discover hidden gems around the globe. From thrilling expeditions to serene getaways, our expert guides ensure every adventure is filled with excitement and cultural enrichment. Unleash your wanderlust and let us craft the perfect escape for you at Wanderlust Adventures.');
INSERT INTO company (name, description) VALUES ('FitLife Technologies', 'Get ready to embrace a healthier lifestyle with FitLife Technologies. We develop cutting-edge fitness tech to revolutionize your workouts and wellness routines. Our wearable devices and mobile apps track your progress, provide personalized training plans, and offer valuable insights into your health. Join our fitness community and embark on a journey towards optimal well-being with FitLife Technologies.');
INSERT INTO company (name, description) VALUES ('AquaGreen Solutions', 'At AquaGreen Solutions, we are committed to preserving and protecting the planet''s most precious resource - water. As water management specialists, we implement sustainable solutions for efficient water usage and treatment. From rainwater harvesting to advanced purification systems, our technologies support a greener future for generations to come. Join us in our mission to create a world where water conservation is a way of life with AquaGreen Solutions.');
INSERT INTO company (name, description) VALUES ('ArtSpace Gallery', 'Welcome to ArtSpace Gallery, a sanctuary for creativity and expression. We showcase a diverse collection of contemporary art from emerging and established artists. Our curated exhibits celebrate artistic talent from various mediums, sparking conversations and inspiring minds. Whether you''re an art enthusiast or a collector, ArtSpace Gallery is where imagination takes flight.');
INSERT INTO company (name, description) VALUES ('TechGuard Cybersecurity', 'Protect your digital assets with TechGuard Cybersecurity, your shield against cyber threats. Our team of cybersecurity experts delivers comprehensive solutions to safeguard businesses and individuals from data breaches and cyberattacks. From network fortification to employee training, our proactive approach ensures robust defense against evolving cyber risks. Partner with TechGuard Cybersecurity and stay ahead in the battle against online vulnerabilities.');
INSERT INTO company (name, description) VALUES ('GreenThumb Landscapes', 'Transform outdoor spaces into breathtaking havens with GreenThumb Landscapes. We specialize in crafting lush gardens and sustainable landscapes that harmonize with nature. Our skilled designers and horticulturists create outdoor retreats tailored to your vision and preferences. Discover the beauty of nature at your doorstep with GreenThumb Landscapes.');
INSERT INTO company (name, description) VALUES ('CloudTech Solutions', 'Embrace the power of the cloud with CloudTech Solutions. As cloud computing pioneers, we offer scalable and secure cloud services for businesses of all sizes. From data storage to application deployment, our cloud solutions streamline operations and enhance collaboration. Experience flexibility and efficiency with CloudTech Solutions, your gateway to the cloud.');
INSERT INTO company (name, description) VALUES ('PetPalooza', 'Celebrate the joy of pet companionship with PetPalooza, your one-stop destination for all things pet-related. From premium pet food to stylish accessories, we cater to the needs of your beloved furry friends. Our passionate team of pet enthusiasts provides expert advice and support to ensure your pets live their best lives. Join our community of pet lovers at PetPalooza and share the love for our animal companions.');
INSERT INTO company (name, description) VALUES ('EcoDrive Motors', 'Step into the future of sustainable transportation with EcoDrive Motors. We design and manufacture electric vehicles that redefine eco-friendly mobility. With cutting-edge battery technology and sleek design, our electric cars deliver an unparalleled driving experience. Join the green revolution and embrace emission-free journeys with EcoDrive Motors.');
INSERT INTO company (name, description) VALUES ('MindWave Technologies', 'Unlock the potential of your mind with MindWave Technologies. We develop brain-computer interface solutions that enable seamless interaction between humans and technology. From mind-controlled applications to neurofeedback training, our innovations open new frontiers in communication and cognitive enhancement. Embrace the future of human-machine integration with MindWave Technologies.');
INSERT INTO company (name, description) VALUES ('GreenEats Catering', 'Savor sustainable and delectable delights with GreenEats Catering. We blend culinary excellence with eco-consciousness, offering farm-to-table experiences that delight the palate and nourish the planet. Our menus feature organic, locally sourced ingredients, and our green practices ensure minimal environmental impact. Taste the difference and experience eco-friendly gastronomy with GreenEats Catering.');
INSERT INTO company (name, description) VALUES ('UrbanDrone Services', 'Take your business to new heights with UrbanDrone Services. We provide aerial solutions for diverse industries, from aerial photography and surveillance to drone-based inspections and logistics. Our licensed drone pilots and advanced technology ensure safe and efficient operations. Explore endless possibilities with UrbanDrone Services.');
INSERT INTO company (name, description) VALUES ('MindfulBuddy', 'Embrace mindfulness and self-care with MindfulBuddy, your digital wellness companion. Our app offers guided meditations, mental health tools, and personal growth resources to support your well-being journey. Cultivate a healthier mind and soul with MindfulBuddy by your side.');
INSERT INTO company (name, description) VALUES ('TechTrek Labs', 'Venture into a world of innovation at TechTrek Labs, where technology and curiosity converge. We foster creativity and collaboration to develop cutting-edge tech solutions, from AI-driven applications to immersive virtual reality experiences. Join us on a journey of discovery and invention with TechTrek Labs.');
INSERT INTO company (name, description) VALUES ('GreenHive Energy', 'Harness the power of the sun with GreenHive Energy, your solar energy partner. We provide comprehensive solar solutions for residential and commercial clients, reducing energy costs while promoting sustainability. Let''s create a cleaner and greener world together with GreenHive Energy.');
INSERT INTO company (name, description) VALUES ('FitBotics', 'Revolutionize your fitness routine with FitBotics, your personal fitness coach in your pocket. Our AI-powered app offers personalized workout plans, real-time feedback, and adaptive training programs. Achieve your fitness goals with science-backed guidance from FitBotics.');
INSERT INTO company (name, description) VALUES ('EnvironCraft', 'Crafting eco-conscious living spaces with EnvironCraft. We design and build sustainable homes that prioritize energy efficiency and environmental harmony. Discover your dream home that treads lightly on the planet with EnvironCraft.');
INSERT INTO company (name, description) VALUES ('StarGaze Entertainment', 'Experience stellar entertainment with StarGaze Entertainment. We produce captivating films, series, and immersive content that transport audiences to new dimensions of storytelling. Let your imagination take flight with StarGaze Entertainment.');
INSERT INTO company (name, description) VALUES ('HealthConnect Solutions', 'Connecting healthcare for a healthier world with HealthConnect Solutions. We develop innovative healthcare technology to improve patient outcomes and streamline medical services. Join us in shaping the future of healthcare with HealthConnect Solutions.');

-- +goose StatementEnd
